version: "3.9"

networks:
  aprsnet:

services:
    direwolf:
        container_name: direwolf
        devices:
        - /dev/bus/usb
        image: w2bro/direwolf:latest
        #      network: host
        restart: always
        environment:
            - CALLSIGN=${CALLSIGN}
            - PASSCODE=${PASSCODE}
            - LATITUDE=${LAT}
            - LONGITUDE=${LONG}
            - IGSERVER=aprsc
            - FREQUENCY=145.175M # Set for australian VHF APRS frequency
        depends_on:
            - aprsc
        networks:
            - aprsnet
    aprsc:
        image: peterus/aprsc:latest
        restart: always
        ports:
        - "10152:10152"
        - "14580:14580"
        - "10155:10155"
        - "14501:14501"
        volumes:
        - $PWD/config/aprsc.conf:/opt/aprsc/etc/aprsc.conf
        networks:
        - aprsnet

    collector:
        image: peterus/trackdirect-python2:latest
        restart: always
        volumes:
        - $PWD/config/trackdirect.ini:/root/trackdirect/config/trackdirect.ini
        command: /root/trackdirect/server/scripts/collector.sh trackdirect.ini 0
        depends_on:
        - "db"
        - "aprsc"
        networks:
        - aprsnet

    websocket:
        image: peterus/trackdirect-python2:latest
        restart: always
        volumes:
        - $PWD/config/trackdirect.ini:/root/trackdirect/config/trackdirect.ini
        command: /root/trackdirect/server/scripts/wsserver.sh trackdirect.ini
        ports:
        - "9000:9000"
        depends_on:
        - "db"
        - "aprsc"
        networks:
        - aprsnet

    heatmaps:
        image: peterus/trackdirect-python2:latest
        restart: always
        volumes:
        - $PWD/config/trackdirect.ini:/root/trackdirect/config/trackdirect.ini
        - $PWD/heatmaps:/root/trackdirect/htdocs/public/heatmaps
        command: /root/trackdirect/server/scripts/heatmapcreator.sh trackdirect.ini /root/trackdirect/htdocs/public/heatmaps
        depends_on:
        - "db"
        networks:
        - aprsnet

    web:
        image: peterus/trackdirect-apache:latest
        restart: always
        volumes:
        - $PWD/config/trackdirect.ini:/root/trackdirect/config/trackdirect.ini
        - $PWD/heatmaps:/root/trackdirect/htdocs/public/heatmaps
        ports:
        - "80:80"
        depends_on:
        - "db"
        networks:
        - aprsnet

    db:
        image: peterus/trackdirect-db:latest
        restart: always
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: foobar
            POSTGRES_DB: trackdirect
        volumes:
        - $PWD/db:/var/lib/postgresql/data
        networks:
        - aprsnet
